; PlatformIO Project Configuration File - Brico Car (Carrinho)
;
; Microcontrolador do Carrinho: Receptor UART + Atuadores + Evaluator
; Hardware atualizado para ESP32 conforme configuracao_carrinho_brico.md
;

[env:carrinho]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_flash = 40000000L
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.3