; PlatformIO Project Configuration File - Brico Box (Caixa)
;
; Microcontrolador da Caixa: Mapeador e Interpretador de Blocos
;

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600